#登陆相关配置
login:
  #开放的模拟登陆api服务器地址, 也可以使用http://localhost:8080/wisedu-unified-login-api-v1.0/api/login, 并在workflows文件中相关取消注释.
  api: "https://api.aqualink.top:6543/wisedu-unified-login-api-v1.0/api/login"

#今日校园相关配置
cpdaily:
  #表单组默认选项配置
  defaults:
    - default:
        title: 今天你的所在地是？
        type: 1
        value: 河南省/周口市/沈丘县
    - default:
        title: 今天你的体温是多少？
        type: 2
        value: 37.2℃及以下
    - default:
        title: 今天你的身体状况是？
        type: 2
        value: 健康
    - default:
        title: 近14天你或你的共同居住人是否有疫情中、高风险区域人员接触史？
        type: 2
        value: 否
    - default:
        title: 近14天你或你的共同居住人是否和确诊、疑似病人接触过？
        type: 2
        value: 否
    - default:
        title: 近14天你或你的共同居住人是否是确诊、疑似病例？
        type: 2
        value: 否
    - default:
        title: 你或你的共同居住人目前是否被医学隔离？
        type: 2
        value: 否
    - default:
        title: 今天你当地的健康码颜色是？
        type: 2
        value: 绿色
    - default:
        title: 本人是否承诺以上所填报的全部内容均属实、准确，不存在任何隐瞒与不实的情况，更无遗漏之处    
        type: 2
        value: 是
