# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - Multi-user
  pull_request:
    branches:
      - Multi-user
  schedule:
    # 每天北京时间8点执行，第二个0代表小时，以此类推，如：9点——'0 1 * * *''
    - cron: '30 0 * * *'

jobs:
  submit:

    runs-on: ubuntu-latest
    environment: TUT

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.6

    - name: Install dependencies
      run: | 
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt

    - name: Run code 
      env:
        # 配置个人信息
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
        address: ${{ secrets.address }}
        school: ${{ secrets.school }}
        # 配置推送信息
        # ServerChan
        sckey: ${{ secrets.sckey }}
        # 使用的config.yml
        config: ${{secrets.config}}

      run: |
        python ./index.py config
